language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
script:
- ./gradlew assembleDebug
- ./gradlew assembleRelease
after_success:
- ls -lh kalturaPlay/build/outputs/apk testapp/build/outputs/apk
- ./pull-artifacts-upload.sh
deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  file:
    - kalturaPlay/build/outputs/apk/kalturaPlay-debug.apk
    - testapp/build/outputs/apk/testapp-debug.apk
  on:
    tags: true
  api-key: $GH_TOKEN
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - itay.kinnrot@kaltura.com
      - nissim.pardo@kaltura.com
    on_success: change
    on_failure: always
    
